"""Tests for salesforce_py.rest.client — RestClient lifecycle + session."""

from __future__ import annotations

import pytest

from salesforce_py.exceptions import AuthError, SalesforcePyError
from salesforce_py.rest._session import RestSession
from salesforce_py.rest.client import RestClient
from salesforce_py.rest.operations import (
    ActionsOperations,
    CompositeOperations,
    LimitsOperations,
    QueryOperations,
    SearchOperations,
    SObjectsOperations,
    ToolingOperations,
    UIAPIOperations,
    VersionsOperations,
)
from tests.rest.conftest import ACCESS_TOKEN, API_VERSION, INSTANCE_URL, make_response


class TestRestSession:
    async def test_open_creates_client(self):
        session = RestSession(INSTANCE_URL, ACCESS_TOKEN)
        await session.open()
        assert session._client is not None
        await session.close()

    async def test_context_manager_opens_and_closes(self):
        session = RestSession(INSTANCE_URL, ACCESS_TOKEN)
        async with session:
            assert session._client is not None
        assert session._client is None

    async def test_get_raises_when_not_open(self):
        session = RestSession(INSTANCE_URL, ACCESS_TOKEN)
        with pytest.raises(RuntimeError, match="not open"):
            await session.get("limits")

    async def test_base_url_is_version_scoped(self):
        session = RestSession(INSTANCE_URL, ACCESS_TOKEN, api_version=API_VERSION)
        await session.open()
        assert str(session._client.base_url) == (
            f"{INSTANCE_URL}/services/data/v{API_VERSION}/"
        )
        await session.close()

    async def test_trailing_slash_is_stripped_from_instance_url(self):
        session = RestSession(f"{INSTANCE_URL}/", ACCESS_TOKEN, api_version=API_VERSION)
        await session.open()
        assert str(session._client.base_url) == (
            f"{INSTANCE_URL}/services/data/v{API_VERSION}/"
        )
        await session.close()


class TestRestClientLifecycle:
    async def test_context_manager(self):
        async with RestClient(INSTANCE_URL, ACCESS_TOKEN) as client:
            assert client._session._client is not None
        assert client._session._client is None

    def test_repr(self):
        client = RestClient(INSTANCE_URL, ACCESS_TOKEN)
        assert INSTANCE_URL in repr(client)

    def test_all_primary_namespaces_attached(self):
        client = RestClient(INSTANCE_URL, ACCESS_TOKEN)
        assert isinstance(client.versions, VersionsOperations)
        assert isinstance(client.limits, LimitsOperations)
        assert isinstance(client.query, QueryOperations)
        assert isinstance(client.search, SearchOperations)
        assert isinstance(client.sobjects, SObjectsOperations)
        assert isinstance(client.composite, CompositeOperations)
        assert isinstance(client.actions, ActionsOperations)
        assert isinstance(client.tooling, ToolingOperations)
        assert isinstance(client.ui_api, UIAPIOperations)

    def test_passthrough_namespaces_attached(self):
        client = RestClient(INSTANCE_URL, ACCESS_TOKEN)
        # Small-surface namespaces generated by the passthrough factory
        for attr in [
            "chatter",
            "commerce",
            "connect",
            "consent",
            "dedupe",
            "jobs",
            "licensing",
            "payments",
            "scheduling",
            "financial_services",
            "health_cloud",
            "manufacturing",
        ]:
            assert hasattr(client, attr), f"missing namespace: {attr}"

    def test_default_timeout_is_120s(self):
        from salesforce_py._retry import DEFAULT_TIMEOUT

        client = RestClient(INSTANCE_URL, ACCESS_TOKEN)
        assert client._session._timeout == DEFAULT_TIMEOUT

    def test_custom_api_version_threaded_through(self):
        client = RestClient(INSTANCE_URL, ACCESS_TOKEN, api_version="63.0")
        assert client._session._api_version == "63.0"


class TestRestBaseHandle:
    def setup_method(self):
        from salesforce_py.rest.base import RestBaseOperations

        self._handle = RestBaseOperations._handle
        self._handle_status = RestBaseOperations._handle_status

    def test_204_returns_empty_dict(self):
        assert self._handle(make_response(204)) == {}

    def test_200_returns_json(self):
        assert self._handle(make_response(200, json_body={"id": "x"})) == {"id": "x"}

    def test_empty_body_returns_empty_dict(self):
        resp = make_response(200)
        # no json_body — content stays empty
        assert self._handle(resp) == {}

    def test_401_raises_auth_error(self):
        with pytest.raises(AuthError):
            self._handle(make_response(401))

    def test_500_raises_salesforce_py_error(self):
        with pytest.raises(SalesforcePyError):
            self._handle(make_response(500, json_body={"message": "server error"}))


class TestDropNone:
    def test_drops_none_values(self):
        from salesforce_py.rest.base import _drop_none

        assert _drop_none({"a": 1, "b": None, "c": "x"}) == {"a": 1, "c": "x"}

    def test_returns_none_when_input_is_none(self):
        from salesforce_py.rest.base import _drop_none

        assert _drop_none(None) is None

    def test_returns_empty_when_input_is_empty(self):
        from salesforce_py.rest.base import _drop_none

        assert _drop_none({}) == {}
